// GENERATED by scripts/compile-mdx.mjs — do not edit by hand.
import Post_01_the_bizarre_sleeping_habits_of_animals from "./01-the-bizarre-sleeping-habits-of-animals.jsx"
import Post_02_the_surprising_origins_of_the_potato_chip from "./02-the-surprising-origins-of-the-potato-chip.jsx"
import Post_03_the_colorful_world_of_synesthesia from "./03-the-colorful-world-of-synesthesia.jsx"

export const mdxComponents: Record<string, React.ComponentType<any>> = {
	"the-bizarre-sleeping-habits-of-animals": Post_01_the_bizarre_sleeping_habits_of_animals,
	"the-surprising-origins-of-the-potato-chip": Post_02_the_surprising_origins_of_the_potato_chip,
	"the-colorful-world-of-synesthesia": Post_03_the_colorful_world_of_synesthesia,
}
