/**
 * Precompile blog MDX files into plain React components at build time.
 *
 * Why: the app used `useMDXComponent(code)` from next-contentlayer, which
 * evaluates the MDX with `new Function(...)`. Cloudflare Workers forbids
 * dynamic code generation, so every post page crashed with "Application error".
 * Compiling to static modules here (Node, at build time) removes all runtime eval.
 *
 * Usage: node scripts/compile-mdx.mjs
 * Output: src/content/compiled/<name>.jsx + src/content/compiled/index.ts
 */
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"
import matter from "gray-matter"
import { compile } from "@mdx-js/mdx"
import remarkGfm from "remark-gfm"
import rehypeSlug from "rehype-slug"
import rehypeAutolinkHeadings from "rehype-autolink-headings"
import rehypePrettyCode from "rehype-pretty-code"

const root = path.dirname(fileURLToPath(import.meta.url))
const blogDir = path.join(root, "..", "src", "content", "blog")
const outDir = path.join(root, "..", "src", "content", "compiled")

// Same slug rule as contentlayer's computed `url` field:
// "01-the-bizarre-sleeping-habits-of-animals" -> "the-bizarre-sleeping-habits-of-animals"
const toSlug = (name) => name.split("-").slice(1).join("-")

const files = (await readdir(blogDir)).filter((f) => f.endsWith(".mdx"))
if (files.length === 0) {
	console.log("No MDX files found, nothing to compile.")
	process.exit(0)
}

await mkdir(outDir, { recursive: true })

const entries = []
for (const file of files) {
	const name = file.replace(/\.mdx$/, "")
	const { content } = matter(await readFile(path.join(blogDir, file), "utf8"))

	const compiled = await compile(content, {
		outputFormat: "program",
		development: false,
		remarkPlugins: [remarkGfm],
		rehypePlugins: [
			rehypeSlug,
			[
				rehypePrettyCode,
				{
					theme: "github-dark",
					onVisitLine(node) {
						if (node.children.length === 0) {
							node.children = [{ type: "text", value: " " }]
						}
					},
					onVisitHighlightedLine(node) {
						node.properties.className.push("line--highlighted")
					},
					onVisitHighlightedWord(node) {
						node.properties.className = ["word--highlighted"]
					},
				},
			],
			[
				rehypeAutolinkHeadings,
				{
					properties: {
						className: ["subheading-anchor"],
						ariaLabel: "Link to section",
					},
				},
			],
		],
	})

	const varName = "Post_" + name.replace(/[^a-zA-Z0-9]/g, "_")
	await writeFile(path.join(outDir, `${name}.jsx`), String(compiled))
	entries.push({ name, slug: toSlug(name), varName })
	console.log(`compiled ${file} -> ${name}.jsx`)
}

const index = `// GENERATED by scripts/compile-mdx.mjs — do not edit by hand.
${entries.map((e) => `import ${e.varName} from "./${e.name}.jsx"`).join("\n")}

export const mdxComponents: Record<string, React.ComponentType<any>> = {
${entries.map((e) => `\t"${e.slug}": ${e.varName},`).join("\n")}
}
`
await writeFile(path.join(outDir, "index.ts"), index)
console.log(`wrote index.ts with ${entries.length} posts`)
